MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
#  WEIGHT: "catalog://Caffe2Detectron/COCO/35861795/e2e_mask_rcnn_R-101-FPN_1x"
  WEIGHT: "/home/wenjing/storage/result/result_nyu12/model_0360000.pth"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 41
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  ROI_DEPTH_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    #    RESOLUTION: 56
    SHARE_BOX_FEATURE_EXTRACTOR: False
    LOSS: 'MSE'
    ADA: "L1"
  WHOLE_DEPTH:
    #    MODEL_OPTION: 'DORN'
    MODEL_OPTION: 'ORIG'
    #    MODEL_OPTION: 'MONO'
    FEATURE_EXTRACTOR: 'FPN'
    PREDICTOR: 'MaskRCNNC4Predictor'
    LOSS: 'MSE'

  MASK_ON: True
  DEPTH_ON: True
  WHOLE_DEPTH_ON: False
  PREPROCESS: False
  decouple: 'independent'

  FREEZE_BOX_MASK: True
  FREEZE_FPN: True
  FREEZE_RPN: True
DATASETS:
  TEST: ("coco_2014_minival",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
